// Code generated by protocol ID generator. DO NOT EDIT.
package pb

// Protocol IDs for Core package messages
const (
	PID_Core_Book uint32 = 0xe11f29d6 // Core.Book
	PID_Core_Fail uint32 = 0xd03670ba // Core.Fail
	PID_Core_Notify_BeAttacked uint32 = 0x8fee7235 // Core.Notify_BeAttacked
	PID_Core_OK uint32 = 0x0ece9291 // Core.OK
	PID_Core_Request_HeartBeat uint32 = 0x95eee555 // Core.Request_HeartBeat
	PID_Core_Request_SearchBook uint32 = 0xd3ecf693 // Core.Request_SearchBook
	PID_Core_Request_SearchBook_Rsp uint32 = 0xf1d19d0a // Core.Request_SearchBook_Rsp
)

// MessageNameToID maps message names to their protocol IDs
var CoreMessageNameToID = map[string]uint32{
	"Book": PID_Core_Book,
	"Fail": PID_Core_Fail,
	"Notify_BeAttacked": PID_Core_Notify_BeAttacked,
	"OK": PID_Core_OK,
	"Request_HeartBeat": PID_Core_Request_HeartBeat,
	"Request_SearchBook": PID_Core_Request_SearchBook,
	"Request_SearchBook_Rsp": PID_Core_Request_SearchBook_Rsp,
}

// IDToMessageName maps protocol IDs to their message names
var CoreIDToMessageName = map[uint32]string{
	PID_Core_Book: "Book",
	PID_Core_Fail: "Fail",
	PID_Core_Notify_BeAttacked: "Notify_BeAttacked",
	PID_Core_OK: "OK",
	PID_Core_Request_HeartBeat: "Request_HeartBeat",
	PID_Core_Request_SearchBook: "Request_SearchBook",
	PID_Core_Request_SearchBook_Rsp: "Request_SearchBook_Rsp",
}

// GetProtocolID returns the protocol ID for the given message name
func GetCoreProtocolID(messageName string) (uint32, bool) {
	id, ok := CoreMessageNameToID[messageName]
	return id, ok
}

// GetMessageName returns the message name for the given protocol ID
func GetCoreMessageName(pid uint32) (string, bool) {
	name, ok := CoreIDToMessageName[pid]
	return name, ok
}
